/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Disk_Details_Child.java
 *
 * Created on 2010/10/24, 下午 08:16:05
 */

package FYP;

import java.awt.Label;
import javax.swing.GroupLayout;

/**
 *
 * @author user
 */
public class Disk_Details_Overall_Child extends javax.swing.JPanel {

    /** Creates new form Disk_Details_Child */
    public Disk_Details_Overall_Child() {
        initComponents();
        jLabel_FAILED.setVisible(false);
        CreateUsageDiagram(100,1);
    }

    public Disk_Details_Overall_Child(int col, int row){
        initComponents();
        CreateUsageDiagram(col,row);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Partition_backup = new javax.swing.JLabel();
        Usage_Panel = new javax.swing.JPanel();
        Disk_Name = new javax.swing.JLabel();
        jLabel_FAILED = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(320, 125));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(140, 100));

        jPanel1.setBackground(new java.awt.Color(220, 234, 247));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 90));

        Partition_backup.setFont(new java.awt.Font("新細明體", 1, 12));
        Partition_backup.setText("Partition:");

        Usage_Panel.setPreferredSize(new java.awt.Dimension(278, 20));

        javax.swing.GroupLayout Usage_PanelLayout = new javax.swing.GroupLayout(Usage_Panel);
        Usage_Panel.setLayout(Usage_PanelLayout);
        Usage_PanelLayout.setHorizontalGroup(
            Usage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        Usage_PanelLayout.setVerticalGroup(
            Usage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Disk_Name.setFont(new java.awt.Font("新細明體", 1, 12));
        Disk_Name.setText("Disk Name");

        jLabel_FAILED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FAILED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/failed_stamp_2.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FAILED, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Partition_backup)
                        .addComponent(Disk_Name)
                        .addComponent(Usage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FAILED)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Disk_Name)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Partition_backup)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Usage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUsageDiagram(int col, int row){
        int i,j;
        label = new Label[col*row];
        for (i = 0; i < col*row; i++){
            label[i] = new Label();
            //label[i].setBackground(new java.awt.Color(0, 102, 153));
            label[i].setBackground(new java.awt.Color(255, 0, 255));
            //label[i].setBackground(Color.RED);
            label[i].setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
        GroupLayout Usage_Layout = new GroupLayout(Usage_Panel);
        Usage_Panel.setLayout(Usage_Layout);
        GroupLayout.SequentialGroup Usage_Horizontal_Group = Usage_Layout.createSequentialGroup();
        GroupLayout.SequentialGroup Usage_Vertical_Group = Usage_Layout.createSequentialGroup();

        for(i = 0; i < col; i++){
            GroupLayout.ParallelGroup PG = Usage_Layout.createParallelGroup();
            for(j = 0; j < row; j++){
                PG.addComponent(label[j*col+i],GroupLayout.PREFERRED_SIZE, 4, GroupLayout.PREFERRED_SIZE);
            }
            Usage_Horizontal_Group.addGroup(PG);
        }

        for(i = 0; i < row; i++){
            GroupLayout.ParallelGroup PG = Usage_Layout.createParallelGroup();
            for(j = 0; j < col; j++){
                PG.addComponent(label[j+row*i],GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE);
            }
            Usage_Vertical_Group.addGroup(PG);
        }

        Usage_Layout.setHorizontalGroup(Usage_Horizontal_Group);
        Usage_Layout.setVerticalGroup(Usage_Vertical_Group);
    }

    public void setLabel(int id, byte used){
        if(used == 0)label[id].setBackground(new java.awt.Color(255, 0, 255));
        else label[id].setBackground(new java.awt.Color(0, 102, 153));
    }

    public void setLabel(int startid, byte used[]){
        int id = startid;
        for(byte usedi : used){
            setLabel(id,usedi);
            id++;
        }
    }

    public void setTitle(String title)
    {
        Disk_Name.setText(title);
    }

    /*public void setFreeSize(int freesize){
        Free_size_text.setText(Integer.toString(freesize));
    }

    public void setFreeSize(String freesize){
        Free_size_text.setText(freesize);
    }

    public void setFreeOffset(int freeoffset){
        Free_offset_text.setText(Integer.toString(freeoffset));
    }

    public void setFreeOffset(String freeoffset){
        Free_offset_text.setText(freeoffset);
    }
    
    public void setTotalSize(int totalsize){
        Total_size_text.setText(Integer.toString(totalsize));
    }

    public void setTotalSize(String totalsize){
        Total_size_text.setText(totalsize);
    }*/

    public void setFail(boolean normal){
        if(!normal){
            jLabel_FAILED.setVisible(true);
        }
        else
            jLabel_FAILED.setVisible(false);
    }

    private Label[] label;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disk_Name;
    private javax.swing.JLabel Partition_backup;
    private javax.swing.JPanel Usage_Panel;
    private javax.swing.JLabel jLabel_FAILED;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
