/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Disk_Details_Child.java
 *
 * Created on 2010/10/24, 下午 08:16:05
 */

package FYP;

import java.awt.Label;
import javax.swing.GroupLayout;

/**
 *
 * @author user
 */
public class Disk_Details_Child extends javax.swing.JPanel {

    /** Creates new form Disk_Details_Child */
    public Disk_Details_Child() {
        initComponents();
        jLabel_FAILED.setVisible(false);
        CreateUsageDiagram(100,1);
    }

    public Disk_Details_Child(int col, int row){
        initComponents();
        CreateUsageDiagram(col,row);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Partition_backup = new javax.swing.JLabel();
        Free_size_text = new javax.swing.JLabel();
        Total_size_text = new javax.swing.JLabel();
        Usage_Panel = new javax.swing.JPanel();
        Total_size_backup = new javax.swing.JLabel();
        _backupFree_size = new javax.swing.JLabel();
        Blue_backup = new java.awt.Label();
        Blue_text_backup = new javax.swing.JLabel();
        Pink_backup = new java.awt.Label();
        Free_offset_text = new javax.swing.JLabel();
        Free_offset_backup = new javax.swing.JLabel();
        Pink_text_backup = new javax.swing.JLabel();
        jLabel_FAILED = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 400));
        setMinimumSize(new java.awt.Dimension(640, 400));
        setPreferredSize(new java.awt.Dimension(640, 400));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 360));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 360));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 360));

        jPanel1.setBackground(new java.awt.Color(220, 234, 247));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        Partition_backup.setFont(new java.awt.Font("新細明體", 1, 12));
        Partition_backup.setText("Partition:");

        Free_size_text.setText("1234");

        Total_size_text.setText("12345678");

        javax.swing.GroupLayout Usage_PanelLayout = new javax.swing.GroupLayout(Usage_Panel);
        Usage_Panel.setLayout(Usage_PanelLayout);
        Usage_PanelLayout.setHorizontalGroup(
            Usage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        Usage_PanelLayout.setVerticalGroup(
            Usage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        Total_size_backup.setFont(new java.awt.Font("新細明體", 1, 12));
        Total_size_backup.setText("Total Size:");

        _backupFree_size.setFont(new java.awt.Font("新細明體", 1, 12));
        _backupFree_size.setText("Free Size:");

        Blue_backup.setBackground(new java.awt.Color(0, 102, 153));
        Blue_backup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Blue_text_backup.setText("Used Space");

        Pink_backup.setBackground(new java.awt.Color(255, 0, 255));
        Pink_backup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Free_offset_text.setText("1234");

        Free_offset_backup.setBackground(new java.awt.Color(153, 255, 255));
        Free_offset_backup.setFont(new java.awt.Font("新細明體", 1, 12));
        Free_offset_backup.setText("Free Offset:");

        Pink_text_backup.setText("Free Space");

        jLabel_FAILED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FAILED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/failed_stamp.gif"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Disk_Details.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_FAILED, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Usage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Total_size_backup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Total_size_text))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(_backupFree_size)
                            .addGap(18, 18, 18)
                            .addComponent(Free_size_text))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Free_offset_backup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Free_offset_text))
                        .addComponent(Partition_backup)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Blue_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Blue_text_backup)
                            .addGap(23, 23, 23)
                            .addComponent(Pink_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Pink_text_backup)))
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_FAILED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Total_size_backup)
                        .addComponent(Total_size_text, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_backupFree_size)
                        .addComponent(Free_size_text))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Free_offset_backup)
                        .addComponent(Free_offset_text))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Partition_backup)
                    .addGap(10, 10, 10)
                    .addComponent(Usage_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Blue_backup, 0, 0, Short.MAX_VALUE)
                        .addComponent(Blue_text_backup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                        .addComponent(Pink_backup, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                        .addComponent(Pink_text_backup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUsageDiagram(int col, int row){
        int i,j;
        label = new Label[col*row];
        for (i = 0; i < col*row; i++){
            label[i] = new Label();
            //label[i].setBackground(new java.awt.Color(0, 102, 153));
            label[i].setBackground(new java.awt.Color(255, 0, 255));
            //label[i].setBackground(Color.RED);
            label[i].setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
        GroupLayout Usage_Layout = new GroupLayout(Usage_Panel);
        Usage_Panel.setLayout(Usage_Layout);
        GroupLayout.SequentialGroup Usage_Horizontal_Group = Usage_Layout.createSequentialGroup();
        GroupLayout.SequentialGroup Usage_Vertical_Group = Usage_Layout.createSequentialGroup();

        for(i = 0; i < col; i++){
            GroupLayout.ParallelGroup PG = Usage_Layout.createParallelGroup();
            for(j = 0; j < row; j++){
                PG.addComponent(label[j*col+i],GroupLayout.PREFERRED_SIZE, 4, GroupLayout.PREFERRED_SIZE);
            }
            Usage_Horizontal_Group.addGroup(PG);
        }

        for(i = 0; i < row; i++){
            GroupLayout.ParallelGroup PG = Usage_Layout.createParallelGroup();
            for(j = 0; j < col; j++){
                PG.addComponent(label[j+row*i],GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE);
            }
            Usage_Vertical_Group.addGroup(PG);
        }

        Usage_Layout.setHorizontalGroup(Usage_Horizontal_Group);
        Usage_Layout.setVerticalGroup(Usage_Vertical_Group);
    }

    public void setLabel(int id, byte used){
        if(used == 0)label[id].setBackground(new java.awt.Color(255, 0, 255));
        else label[id].setBackground(new java.awt.Color(0, 102, 153));
    }

    public void setLabel(int startid, byte used[]){
        int id = startid;
        for(byte usedi : used){
            setLabel(id,usedi);
            id++;
        }
    }

    public void setFreeSize(int freesize){
        Free_size_text.setText(Integer.toString(freesize));
    }

    public void setFreeSize(String freesize){
        Free_size_text.setText(freesize);
    }

    public void setFreeOffset(int freeoffset){
        Free_offset_text.setText(Integer.toString(freeoffset));
    }

    public void setFreeOffset(String freeoffset){
        Free_offset_text.setText(freeoffset);
    }
    
    public void setTotalSize(int totalsize){
        Total_size_text.setText(Integer.toString(totalsize));
    }

    public void setTotalSize(String totalsize){
        Total_size_text.setText(totalsize);
    }

    public void setFail(boolean normal){
        if(!normal){
            jLabel_FAILED.setVisible(true);
        }
        else
            jLabel_FAILED.setVisible(false);
    }

    private Label[] label;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Blue_backup;
    private javax.swing.JLabel Blue_text_backup;
    private javax.swing.JLabel Free_offset_backup;
    private javax.swing.JLabel Free_offset_text;
    private javax.swing.JLabel Free_size_text;
    private javax.swing.JLabel Partition_backup;
    private java.awt.Label Pink_backup;
    private javax.swing.JLabel Pink_text_backup;
    private javax.swing.JLabel Total_size_backup;
    private javax.swing.JLabel Total_size_text;
    private javax.swing.JPanel Usage_Panel;
    private javax.swing.JLabel _backupFree_size;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_FAILED;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
