/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FYP_GUI.java
 *
 * Created on Oct 5, 2010, 12:43:31 PM
 */

package FYP;

import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Administrator
 */
//public class FYP_GUI extends javax.swing.JFrame {
public class FYP_GUI extends javax.swing.JFrame {

    /** Creates new form FYP_GUI */
    public FYP_GUI(java.awt.Frame parent, boolean modal, String IP_Address) {
    //public FYP_GUI() {
        //super(parent, modal);
        super();
        
        setTitle("FYP GUI");
        initComponents();
        
        Global.Wel = new Welcome(this, true);
        Global.Wel.setVisible(true);

        System.out.println(IP_Address);

        //Tab.removeAll();

        if (Global.testing)
            Global.sd = new Network_Layer(IP_Address,1234);

        Global.DiskDetails = new Disk_Details();
        
        Global.SetupDetails = new Setup_Details();
        Tab.addTab("Setup Details", Global.SetupDetails);

        Tab.addTab("Disk Details", Global.DiskDetails);

        //Global.DiskDetails = new Disk_Details();
        //Tab.addTab("Disk Details 2", Global.DiskDetails);
        /*for(int i = 0; i < 4; ++i){
            Disk_Details_Child DD = new Disk_Details_Child();
            Global.DiskDetails.add_Tab("Disk " + i, DD);
        }*/

        Global.ContentBrowser = new Content_Browser();
        Tab.addTab("Content Browser", Global.ContentBrowser);

        Global.RecoveryProcess = new Recovery_Process();
        Tab.addTab("Recovery Process", Global.RecoveryProcess);

        Global.TopLevelProcess = new Top_Level_Process();
        Tab.addTab("Top Level Process", Global.TopLevelProcess);

        Global.RenameText = new Rename(this, true);
        Global.RenameText.setVisible(false);

        /*String[] RP_str = {"/dev/loop1", "/dev/loop2", "/dev/loop3", "/dev/loop4", "/dev/loop5"};
        Global.RecoveryProcess.setLabel(4, RP_str);
        Global.RecoveryProcess.start_to_run();
        Global.RecoveryProcess.stop();*/

        // Center in the screen
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //Dimension frameSize = getSize();
        Global.screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Global.frameSize = getSize();
        setLocation(new Point((Global.screenSize.width - Global.frameSize.width) / 2,
                              (Global.screenSize.height - Global.frameSize.height) / 2));
        Command_Dispatcher CommandDispatcher = new Command_Dispatcher();
        new Thread(CommandDispatcher).start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diskdetailtab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tab = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        jLabel1.setText("free offset");

        jLabel2.setText("free offset");

        jLabel3.setText("free offset");

        jLabel4.setText("free offset");

        javax.swing.GroupLayout diskdetailtabLayout = new javax.swing.GroupLayout(diskdetailtab);
        diskdetailtab.setLayout(diskdetailtabLayout);
        diskdetailtabLayout.setHorizontalGroup(
            diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diskdetailtabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addContainerGap(371, Short.MAX_VALUE)))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel3)
                    .addContainerGap(361, Short.MAX_VALUE)))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel4)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );
        diskdetailtabLayout.setVerticalGroup(
            diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diskdetailtabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel2)
                    .addContainerGap(327, Short.MAX_VALUE)))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel3)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(diskdetailtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(diskdetailtabLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel4)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab.setMaximumSize(new java.awt.Dimension(640, 480));
        Tab.setMinimumSize(new java.awt.Dimension(640, 480));
        Tab.setPreferredSize(new java.awt.Dimension(640, 480));
        Tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabStateChanged(evt);
            }
        });

        File.setText("File");

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        Edit.setBackground(new java.awt.Color(236, 233, 216));
        Edit.setText("Edit");
        jMenuBar1.add(Edit);

        Help.setText("Help");

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        new About(this,true).setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void TabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabStateChanged
        // TODO add your handling code here:
        /*if (Tab.getSelectedComponent()== Global.ContentBrowser)
            if(Global.ContentBrowser != null)
          
            Global.ContentBrowser.RefreshContent();*/
    }//GEN-LAST:event_TabStateChanged

    /**
    * @param args the command line arguments
    */

    ////////////////////////////////////////////////////////
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FYP_GUI().setVisible(true);
            }
        });
    }*/
    //////////////////////////////////////////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JPanel diskdetailtab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}