/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on 2010年10月5日, 下午07:55:34
 */

package FYP;

//import FYP.About;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Andrew Kong
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form FYP_GUI */
    public Login() {
        setTitle("FYP GUI Login");
        initComponents();
        LoginWord.setText("fyp");
        PasswordWord.setText("123");

        LoginWord.requestFocusInWindow();

        setContentPane(wrapInBackgroundImage(jPanel_Login, new ImageIcon(
                //getClass().getResource("/Resourses/mac_os_x_leopard_space.jpg"))));
                //getClass().getResource("/Resourses/rainbow.jpg"))));
                //getClass().getResource("/Resourses/ECFS_middle.jpg"))));
                getClass().getResource("/Resourses/ECFS_background.png"))));

        // Center in the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                              (screenSize.height - frameSize.height) / 2));
    }

    private static final GridBagConstraints gbc;
    static {
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.anchor = GridBagConstraints.NORTHWEST;
    }

    public static JPanel wrapInBackgroundImage(JComponent component,
            Icon backgroundIcon) {
        return wrapInBackgroundImage(
                component,
                backgroundIcon,
                JLabel.TOP,
                JLabel.LEADING);
    }

    public static JPanel wrapInBackgroundImage(JComponent component,
            Icon backgroundIcon,
            int verticalAlignment,
            int horizontalAlignment) {

        // make the passed in swing component transparent
        component.setOpaque(false);

        // create wrapper JPanel
        JPanel backgroundPanel = new JPanel(new GridBagLayout());

        // add the passed in swing component first to ensure that it is in front
        backgroundPanel.add(component, gbc);

        // create a label to paint the background image
        JLabel backgroundImage = new JLabel(backgroundIcon);

        // set minimum and preferred sizes so that the size of the image
        // does not affect the layout size
        //backgroundImage.setPreferredSize(new Dimension(1,1));
        //backgroundImage.setMinimumSize(new Dimension(1,1));
        backgroundImage.setPreferredSize(new Dimension(1,1));

        // align the image as specified.
        backgroundImage.setVerticalAlignment(verticalAlignment);
        backgroundImage.setHorizontalAlignment(horizontalAlignment);

        // add the background label
        backgroundPanel.add(backgroundImage, gbc);

        // return the wrapper
        return backgroundPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ECFS_CLIENT_GUI = new javax.swing.JLabel();
        statement = new javax.swing.JLabel();
        jPanel_Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        PasswordWord = new javax.swing.JPasswordField();
        Close = new javax.swing.JButton();
        ReplyLabel = new javax.swing.JLabel();
        LoginWord = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        login_icon = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        IPLabel = new javax.swing.JLabel();
        IPWord = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        File2 = new javax.swing.JMenu();
        Exit2 = new javax.swing.JMenuItem();
        Help1 = new javax.swing.JMenu();
        About1 = new javax.swing.JMenuItem();

        ECFS_CLIENT_GUI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ECFS_CLIENT_GUI.setText("ECFS CLIENT GUI");

        statement.setText("A GUI for client interface based on the Swing Application Framework");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_Login.setPreferredSize(new java.awt.Dimension(420, 390));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        PasswordWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordWordActionPerformed(evt);
            }
        });

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        ReplyLabel.setText(" ");

        LoginWord.setColumns(20);
        LoginWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginWordActionPerformed(evt);
            }
        });

        PasswordLabel.setDisplayedMnemonic('Y');
        PasswordLabel.setText("Password:");

        login_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/login_icon_2.gif"))); // NOI18N
        login_icon.setMinimumSize(new java.awt.Dimension(300, 500));
        login_icon.setPreferredSize(new java.awt.Dimension(300, 500));

        LoginLabel.setText("Login ID:");

        IPLabel.setDisplayedMnemonic('Y');
        IPLabel.setText("IP address: ");

        IPWord.setColumns(20);
        IPWord.setText("127.0.0.1");
        IPWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LoginLayout = new javax.swing.GroupLayout(jPanel_Login);
        jPanel_Login.setLayout(jPanel_LoginLayout);
        jPanel_LoginLayout.setHorizontalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LoginLayout.createSequentialGroup()
                        .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel)
                            .addComponent(PasswordLabel)
                            .addComponent(IPLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LoginLayout.createSequentialGroup()
                                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PasswordWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(IPWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(LoginWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(login_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                                .addComponent(ReplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginButton)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                        .addComponent(Close)
                        .addContainerGap())))
        );
        jPanel_LoginLayout.setVerticalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(login_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IPLabel))
                .addGap(11, 11, 11)
                .addGroup(jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReplyLabel)
                    .addComponent(LoginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close)
                .addContainerGap())
        );

        File2.setText("File");

        Exit2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        Exit2.setText("Exit");
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        File2.add(Exit2);

        jMenuBar1.add(File2);

        Help1.setText("Help");

        About1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        About1.setText("About");
        About1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About1ActionPerformed(evt);
            }
        });
        Help1.add(About1);

        jMenuBar1.add(Help1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginWordActionPerformed
        // TODO add your handling code here:
        String password = new String(PasswordWord.getPassword());
        if (LoginWord.getText().equals("fyp"))
        {
            if (password.equals("123"))
            {
                this.setVisible(false);
                new FYP_GUI(this,true,IPWord.getText()).setVisible(true);
            }
            else
            {
                ReplyLabel.setText("Incorrect password! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
            }
        }
        else
        {
                ReplyLabel.setText("Incorrect login ID! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
        }
        LoginWord.requestFocusInWindow();
    }//GEN-LAST:event_LoginWordActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_CloseActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String password = new String(PasswordWord.getPassword());
        if (LoginWord.getText().equals("fyp"))
        {
            if (password.equals("123"))
            {
                this.setVisible(false);
                new FYP_GUI(this,true,IPWord.getText()).setVisible(true);
            }
            else
            {
                ReplyLabel.setText("Incorrect password! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
            }
        }
        else
        {
                ReplyLabel.setText("Incorrect login ID! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
        }
        LoginWord.requestFocusInWindow();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_Exit2ActionPerformed

    private void About1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About1ActionPerformed
        // TODO add your handling code here:
        new About(this,true).setVisible(true);
}//GEN-LAST:event_About1ActionPerformed

    private void PasswordWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordWordActionPerformed
        // TODO add your handling code here:
        String password = new String(PasswordWord.getPassword());
        if (LoginWord.getText().equals("fyp"))
        {
            if (password.equals("123"))
            {
                this.setVisible(false);
                new FYP_GUI(this,true,IPWord.getText()).setVisible(true);
            }
            else
            {
                ReplyLabel.setText("Incorrect password! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
            }
        }
        else
        {
                ReplyLabel.setText("Incorrect login ID! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
        }
        LoginWord.requestFocusInWindow();
    }//GEN-LAST:event_PasswordWordActionPerformed

    private void IPWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPWordActionPerformed
        // TODO add your handling code here:
        String password = new String(PasswordWord.getPassword());
        if (LoginWord.getText().equals("fyp"))
        {
            if (password.equals("123"))
            {
                this.setVisible(false);
                new FYP_GUI(this,true,IPWord.getText()).setVisible(true);
            }
            else
            {
                ReplyLabel.setText("Incorrect password! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
            }
        }
        else
        {
                ReplyLabel.setText("Incorrect login ID! Try again!");
                LoginWord.setText("");
                PasswordWord.setText("");
        }
        LoginWord.requestFocusInWindow();
    }//GEN-LAST:event_IPWordActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About1;
    private javax.swing.JButton Close;
    private javax.swing.JLabel ECFS_CLIENT_GUI;
    private javax.swing.JMenuItem Exit2;
    private javax.swing.JMenu File2;
    private javax.swing.JMenu Help1;
    private javax.swing.JLabel IPLabel;
    private javax.swing.JTextField IPWord;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField LoginWord;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordWord;
    private javax.swing.JLabel ReplyLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel_Login;
    private javax.swing.JLabel login_icon;
    private javax.swing.JLabel statement;
    // End of variables declaration//GEN-END:variables
}
