/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Top_Level_Process.java
 *
 * Created on 2010/10/27, 下午 10:56:03
 */

package FYP;

import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
/**
 *
 * @author user
 */
public class Top_Level_Process extends javax.swing.JPanel {

    /** Creates new form Top_Level_Process */
    public Top_Level_Process() {
        initComponents();
    }

    private enum Stage{
        DISK2CACHE, CACHE2FILE, FILE2SERVER, SERVER2CLIENT
    }

    public void ProcessHandler(){
        Stage instage;
        boolean working;
        byte inbyte;
        byte inbyte2;
        try{
            inbyte = Global.sd.ReadByte();
            inbyte2 = Global.sd.ReadByte();
        } catch (IOException e) {
            return;
        }
        switch(inbyte){
            case 0: instage = Stage.DISK2CACHE;break;
            case 1: instage = Stage.CACHE2FILE;break;
            case 2: instage = Stage.FILE2SERVER;break;
            case 3: instage = Stage.SERVER2CLIENT;break;
            default: return;
        }
        if(inbyte2 == 1)
            working = true;
        else
            working = false;
        StartProcess(instage,working);
    }

    private void StartProcess(Stage instage, boolean working){
        JLabel StageLabel;
        ImageIcon StageIcon;
        switch(instage){
            case DISK2CACHE:   StageLabel = Disk2Cache;break;
            case CACHE2FILE:   StageLabel = Cache2File;break;
            case FILE2SERVER:   StageLabel = File2Server;break;
            case SERVER2CLIENT: StageLabel = Server2Client;break;
            default: return;
        }

        if(working == true)
            StageIcon = new ImageIcon(getClass().getResource("/Resourses/arrow-up-icon-w.gif"));
        else
            StageIcon = new ImageIcon(getClass().getResource("/Resourses/Up_arrow.gif"));

        SwingUtilities.invokeLater(new ChangeIcon(StageLabel,StageIcon));
        return;
    }

    /**
     * @brief   Update the GUI after the event-dispatching thread
     */
    private class ChangeIcon implements Runnable{
        private JLabel TargetLabel;
        private ImageIcon InIcon;
        ChangeIcon(JLabel target, ImageIcon inicon){
            TargetLabel = target;
            InIcon = inicon;
        }
        public void run() {
            TargetLabel.setIcon(InIcon);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TopLevel_Process = new javax.swing.JPanel();
        File2Server = new javax.swing.JLabel();
        Cache2File = new javax.swing.JLabel();
        Disk2Cache = new javax.swing.JLabel();
        Server2Client = new javax.swing.JLabel();
        Disk_Box = new javax.swing.JPanel();
        status9 = new javax.swing.JLabel();
        Cache_Box = new javax.swing.JPanel();
        status5 = new javax.swing.JLabel();
        File_Box = new javax.swing.JPanel();
        status6 = new javax.swing.JLabel();
        Client_Box = new javax.swing.JPanel();
        status7 = new javax.swing.JLabel();
        Server_Box = new javax.swing.JPanel();
        status8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        TopLevel_Process.setBackground(new java.awt.Color(220, 234, 247));
        TopLevel_Process.setMaximumSize(new java.awt.Dimension(600, 400));
        TopLevel_Process.setMinimumSize(new java.awt.Dimension(600, 400));
        TopLevel_Process.setPreferredSize(new java.awt.Dimension(600, 400));

        File2Server.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Up_arrow.gif"))); // NOI18N

        Cache2File.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Up_arrow.gif"))); // NOI18N

        Disk2Cache.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Up_arrow.gif"))); // NOI18N

        Server2Client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Up_arrow.gif"))); // NOI18N

        Disk_Box.setBackground(new java.awt.Color(0, 0, 204));

        status9.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        status9.setForeground(new java.awt.Color(255, 255, 255));
        status9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/disk_24.png"))); // NOI18N
        status9.setText("Disk Layer");

        javax.swing.GroupLayout Disk_BoxLayout = new javax.swing.GroupLayout(Disk_Box);
        Disk_Box.setLayout(Disk_BoxLayout);
        Disk_BoxLayout.setHorizontalGroup(
            Disk_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Disk_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status9, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        Disk_BoxLayout.setVerticalGroup(
            Disk_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Disk_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Cache_Box.setBackground(new java.awt.Color(0, 51, 255));

        status5.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        status5.setForeground(new java.awt.Color(255, 255, 255));
        status5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/cache_icon.png"))); // NOI18N
        status5.setText("Cache Layer");

        javax.swing.GroupLayout Cache_BoxLayout = new javax.swing.GroupLayout(Cache_Box);
        Cache_Box.setLayout(Cache_BoxLayout);
        Cache_BoxLayout.setHorizontalGroup(
            Cache_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cache_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Cache_BoxLayout.setVerticalGroup(
            Cache_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cache_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        File_Box.setBackground(new java.awt.Color(0, 102, 255));

        status6.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        status6.setForeground(new java.awt.Color(255, 255, 255));
        status6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/New_24x24.png"))); // NOI18N
        status6.setText("File");

        javax.swing.GroupLayout File_BoxLayout = new javax.swing.GroupLayout(File_Box);
        File_Box.setLayout(File_BoxLayout);
        File_BoxLayout.setHorizontalGroup(
            File_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_BoxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(status6)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        File_BoxLayout.setVerticalGroup(
            File_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Client_Box.setBackground(new java.awt.Color(102, 204, 255));

        status7.setFont(new java.awt.Font("新細明體", 1, 12));
        status7.setForeground(new java.awt.Color(255, 255, 255));
        status7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/User_24x24.png"))); // NOI18N
        status7.setText("Client");

        javax.swing.GroupLayout Client_BoxLayout = new javax.swing.GroupLayout(Client_Box);
        Client_Box.setLayout(Client_BoxLayout);
        Client_BoxLayout.setHorizontalGroup(
            Client_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Client_BoxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(status7)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Client_BoxLayout.setVerticalGroup(
            Client_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Client_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Server_Box.setBackground(new java.awt.Color(51, 153, 255));

        status8.setFont(new java.awt.Font("新細明體", 1, 12));
        status8.setForeground(new java.awt.Color(255, 255, 255));
        status8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/black-server-icon.png"))); // NOI18N
        status8.setText("Server");

        javax.swing.GroupLayout Server_BoxLayout = new javax.swing.GroupLayout(Server_Box);
        Server_Box.setLayout(Server_BoxLayout);
        Server_BoxLayout.setHorizontalGroup(
            Server_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Server_BoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(status8)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Server_BoxLayout.setVerticalGroup(
            Server_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Server_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/ECFS.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/Top_Level_Process.png"))); // NOI18N

        javax.swing.GroupLayout TopLevel_ProcessLayout = new javax.swing.GroupLayout(TopLevel_Process);
        TopLevel_Process.setLayout(TopLevel_ProcessLayout);
        TopLevel_ProcessLayout.setHorizontalGroup(
            TopLevel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(TopLevel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Server2Client))
                    .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                        .addGroup(TopLevel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Disk_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Server_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Client_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(File_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cache_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopLevel_ProcessLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(File2Server))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopLevel_ProcessLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Cache2File))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopLevel_ProcessLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Disk2Cache)))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopLevel_ProcessLayout.setVerticalGroup(
            TopLevel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLevel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                        .addComponent(Client_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Server2Client)
                        .addGap(6, 6, 6)
                        .addComponent(Server_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(File2Server)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(File_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cache2File)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cache_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Disk2Cache)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Disk_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(TopLevel_ProcessLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(TopLevel_Process);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cache2File;
    private javax.swing.JPanel Cache_Box;
    private javax.swing.JPanel Client_Box;
    private javax.swing.JLabel Disk2Cache;
    private javax.swing.JPanel Disk_Box;
    private javax.swing.JLabel File2Server;
    private javax.swing.JPanel File_Box;
    private javax.swing.JLabel Server2Client;
    private javax.swing.JPanel Server_Box;
    private javax.swing.JPanel TopLevel_Process;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel status5;
    private javax.swing.JLabel status6;
    private javax.swing.JLabel status7;
    private javax.swing.JLabel status8;
    private javax.swing.JLabel status9;
    // End of variables declaration//GEN-END:variables

}
